# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-22 05:22
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrations', '0003_registration_mother_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mother_id', models.CharField(max_length=36)),
                ('action', models.CharField(choices=[('change_messaging', 'Change messaging type and/or reception times'), ('change_loss', 'Change to loss messaging'), ('unsubscribe_household_only', 'Unsubscribe household msg receiver'), ('unsubscribe_mother_only', 'Unsubscribe mother from messages'), ('change_language', 'Change language'), ('change_baby', 'Change to baby messages')], max_length=255)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changes_created', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='registrations.Source')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changes_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
