# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-08-16 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.CharField(max_length=30)),
                ('end_date', models.CharField(max_length=30)),
                ('email_subject', models.CharField(max_length=100)),
                ('file_size', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[(b'Pending', b'Pending'), (b'Running', b'Running'), (b'Sending', b'Sending'), (b'Done', b'Done')], max_length=30)),
                ('error', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
