# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-23 12:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_registration_mother_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionrequest',
            old_name='messageset_id',
            new_name='messageset',
        ),
    ]
