# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-30 13:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_auto_20160323_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionrequest',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
