# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-03-23 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_thirdpartyregistrationerror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='stage',
            field=models.CharField(choices=[(b'prebirth', b'Mother is pregnant'), (b'postbirth', b'Baby has been born'), (b'loss', b'Baby loss'), (b'public', b'Public')], max_length=30),
        ),
    ]
