# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-09-27 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('shortcode', models.CharField(max_length=36)),
                ('msisdn', models.CharField(max_length=36)),
                ('duration', models.IntegerField()),
                ('reason', models.CharField(max_length=36)),
            ],
        ),
    ]
