# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-14 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vas2nets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicecall',
            name='created_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='voicecall',
            name='msisdn',
            field=models.CharField(db_index=True, max_length=36),
        ),
    ]
